on: [push, pull_request, workflow_dispatch]

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.short_sha.outputs.result }}
    steps:
      - name: Get short SHA
        id: short_sha
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: return context.sha.substring(0, 7)

  build:
    needs: prepare
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      archive_name: "firmware-${{ needs.prepare.outputs.short_sha }}"
